"""Send Am V2.5/V3 Expansion: WakaShare, Milestones, and Verification

Revision ID: 0fe4560d12a5
Revises: 4f5161ef9dd1
Create Date: 2026-04-05 06:24:58.331775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0fe4560d12a5'
down_revision: Union[str, Sequence[str], None] = '4f5161ef9dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('equipment', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(length=20), server_default='unverified', nullable=False))
    op.add_column('users', sa.Column('verification_ref', sa.String(length=100), nullable=True))
    op.add_column('wakas', sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('wakas', sa.Column('parent_waka_id', sa.UUID(), nullable=True))
    op.add_column('wakas', sa.Column('max_spots', sa.Integer(), server_default='1', nullable=False))
    op.add_column('wakas', sa.Column('milestones', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'wakas', 'wakas', ['parent_waka_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wakas', type_='foreignkey')
    op.drop_column('wakas', 'milestones')
    op.drop_column('wakas', 'max_spots')
    op.drop_column('wakas', 'parent_waka_id')
    op.drop_column('wakas', 'is_shared')
    op.drop_column('users', 'verification_ref')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'equipment')
    # ### end Alembic commands ###
