"""add_runner_rate_and_is_available

Revision ID: 18f1231c3e6b
Revises: 9925713d972b
Create Date: 2026-04-04 03:52:22.512342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '18f1231c3e6b'
down_revision: Union[str, Sequence[str], None] = '9925713d972b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runner_applications', sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    
    # Add is_available as nullable first to handle existing data
    op.add_column('users', sa.Column('is_available', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE users SET is_available = FALSE")
    
    # Set to NOT NULL
    op.alter_column('users', 'is_available', nullable=False)
    
    op.create_index(op.f('ix_users_is_available'), 'users', ['is_available'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_available'), table_name='users')
    op.drop_column('users', 'is_available')
    op.drop_column('runner_applications', 'hourly_rate')
    # ### end Alembic commands ###
