"""add_is_deleted_to_support_message

Revision ID: 1a050cce0bf1
Revises: dcd2a33d4b9d
Create Date: 2026-04-03 02:43:21.735946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1a050cce0bf1'
down_revision: Union[str, Sequence[str], None] = 'dcd2a33d4b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('attachment_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_support_messages_is_deleted'), table_name='support_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_support_messages_is_deleted'), 'support_messages', ['is_deleted'], unique=False)
    op.drop_column('support_messages', 'attachment_metadata')
    # ### end Alembic commands ###
