"""Add surge pricing metrics

Revision ID: 290afc68a0b0
Revises: 2b759d8058fb
Create Date: 2026-04-05 10:20:20.568361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '290afc68a0b0'
down_revision: Union[str, Sequence[str], None] = '2b759d8058fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wakas', sa.Column('surge_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False))
    op.add_column('wakas', sa.Column('surge_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'surge_reason')
    op.drop_column('wakas', 'surge_multiplier')
    # ### end Alembic commands ###
