"""Add safe drop lockers

Revision ID: 2b759d8058fb
Revises: 81d7ec506b0f
Create Date: 2026-04-05 10:13:36.019305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2b759d8058fb'
down_revision: Union[str, Sequence[str], None] = '81d7ec506b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wakas', sa.Column('drop_type', sa.String(length=20), server_default='doorstep', nullable=False))
    op.add_column('wakas', sa.Column('safe_drop_pin', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'safe_drop_pin')
    op.drop_column('wakas', 'drop_type')
    # ### end Alembic commands ###
