"""Send Am V2 Expansion: Disputes, Addresses, Bookmarks, and POD

Revision ID: 4f5161ef9dd1
Revises: 1029caeaa73b
Create Date: 2026-04-05 06:17:40.278184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4f5161ef9dd1'
down_revision: Union[str, Sequence[str], None] = '1029caeaa73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wakas', sa.Column('pod_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'pod_url')
    # ### end Alembic commands ###
