"""add_v2_features

Revision ID: 4f5834e62cf6
Revises: 54facd0517dd
Create Date: 2026-04-05 05:17:16.977987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4f5834e62cf6'
down_revision: Union[str, Sequence[str], None] = '54facd0517dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('lat', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('lng', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_is_deleted'), 'user_addresses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('user_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bookmarks_is_deleted'), 'user_bookmarks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_target_user_id'), 'user_bookmarks', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_user_id'), 'user_bookmarks', ['user_id'], unique=False)
    op.create_table('waka_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waka_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waka_id'], ['wakas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waka_disputes_is_deleted'), 'waka_disputes', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    op.add_column('wakas', sa.Column('insurance_opt_in', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'insurance_opt_in')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')
    op.drop_index(op.f('ix_waka_disputes_is_deleted'), table_name='waka_disputes')
    op.drop_table('waka_disputes')
    op.drop_index(op.f('ix_user_bookmarks_user_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_target_user_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_is_deleted'), table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_is_deleted'), table_name='user_addresses')
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
