"""add more user preferences

Revision ID: 528c024e5e95
Revises: b5bafbd3c52d
Create Date: 2026-04-02 04:19:14.422213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '528c024e5e95'
down_revision: Union[str, Sequence[str], None] = 'b5bafbd3c52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server default to handle existing rows
    op.add_column('users', sa.Column('is_dark_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('users', sa.Column('region', sa.String(length=10), server_default='NG', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    op.drop_column('users', 'language')
    op.drop_column('users', 'is_dark_mode')
    # ### end Alembic commands ###
