"""add is_cash to transaction

Revision ID: 54facd0517dd
Revises: f933e2ddf2d6
Create Date: 2026-04-05 04:54:51.271748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '54facd0517dd'
down_revision: Union[str, Sequence[str], None] = 'f933e2ddf2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_cash', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_cash')
    # ### end Alembic commands ###
