"""add_is_user_deleted_flag

Revision ID: 5a0f95a5bf3c
Revises: cf8b4143fc6b
Create Date: 2026-04-02 05:29:13.743204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5a0f95a5bf3c'
down_revision: Union[str, Sequence[str], None] = 'cf8b4143fc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_user_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_user_deleted')
    # ### end Alembic commands ###
