"""Send Am V3 Expansion: Scheduled Wakas and Live Inventory

Revision ID: 5fc7855462e6
Revises: 0fe4560d12a5
Create Date: 2026-04-05 06:28:42.922321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5fc7855462e6'
down_revision: Union[str, Sequence[str], None] = '0fe4560d12a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_wakas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('waka_template', sa.JSON(), nullable=False),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_wakas_is_deleted'), 'scheduled_wakas', ['is_deleted'], unique=False)
    op.create_table('waka_inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waka_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_ordered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['waka_id'], ['wakas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waka_inventory_items_is_deleted'), 'waka_inventory_items', ['is_deleted'], unique=False)
    op.add_column('wakas', sa.Column('original_runner_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'original_runner_fee')
    op.drop_index(op.f('ix_waka_inventory_items_is_deleted'), table_name='waka_inventory_items')
    op.drop_table('waka_inventory_items')
    op.drop_index(op.f('ix_scheduled_wakas_is_deleted'), table_name='scheduled_wakas')
    op.drop_table('scheduled_wakas')
    # ### end Alembic commands ###
