"""add_runner_application_and_is_runner_flag

Revision ID: 6602dff81da7
Revises: a03e3db62055
Create Date: 2026-04-02 05:09:46.564283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6602dff81da7'
down_revision: Union[str, Sequence[str], None] = 'a03e3db62055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bvn', sa.String(length=11), nullable=True),
    sa.Column('home_address', sa.String(length=512), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('verification_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.String(length=512), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runner_applications_is_deleted'), 'runner_applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_runner_applications_user_id'), 'runner_applications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_runner', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_runner')
    op.drop_index(op.f('ix_runner_applications_user_id'), table_name='runner_applications')
    op.drop_index(op.f('ix_runner_applications_is_deleted'), table_name='runner_applications')
    op.drop_table('runner_applications')
    # ### end Alembic commands ###
