"""use_decimal_for_wallets

Revision ID: 81d7ec506b0f
Revises: ef69fb32e776
Create Date: 2026-04-05 06:51:17.947363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '81d7ec506b0f'
down_revision: Union[str, Sequence[str], None] = 'ef69fb32e776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
