"""Add stats_rating to users

Revision ID: 885f1ca3d905
Revises: f3e1ada82d8d
Create Date: 2026-04-02 04:47:33.604259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '885f1ca3d905'
down_revision: Union[str, Sequence[str], None] = 'f3e1ada82d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stats_rating', sa.Numeric(precision=3, scale=2), server_default=sa.text('5.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stats_rating')
    # ### end Alembic commands ###
