"""Add voice note and waypoints to waka

Revision ID: 88b6ece8579e
Revises: 88ba5de62f3b
Create Date: 2026-04-05 10:51:49.093324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '88b6ece8579e'
down_revision: Union[str, Sequence[str], None] = '88ba5de62f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wakas', sa.Column('waypoints', sa.JSON(), nullable=True))
    op.add_column('wakas', sa.Column('voice_note_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'voice_note_url')
    op.drop_column('wakas', 'waypoints')
    # ### end Alembic commands ###
