"""Add runner streaks and fee discount

Revision ID: 88ba5de62f3b
Revises: 290afc68a0b0
Create Date: 2026-04-05 10:23:43.042304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '88ba5de62f3b'
down_revision: Union[str, Sequence[str], None] = '290afc68a0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_streak_update', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('platform_fee_discount', sa.Numeric(precision=4, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform_fee_discount')
    op.drop_column('users', 'last_streak_update')
    op.drop_column('users', 'streak_count')
    # ### end Alembic commands ###
