"""add_waka_decline_and_completion_flags

Revision ID: 9577a68c966d
Revises: aa370d745ce5
Create Date: 2026-04-03 11:18:53.411886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9577a68c966d'
down_revision: Union[str, Sequence[str], None] = 'aa370d745ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waka_declines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waka_id', sa.UUID(), nullable=False),
    sa.Column('runner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waka_id'], ['wakas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waka_declines_is_deleted'), 'waka_declines', ['is_deleted'], unique=False)
    op.add_column('wakas', sa.Column('completed_by_runner', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('wakas', sa.Column('completed_by_employer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'completed_by_employer')
    op.drop_column('wakas', 'completed_by_runner')
    op.drop_index(op.f('ix_waka_declines_is_deleted'), table_name='waka_declines')
    op.drop_table('waka_declines')
    # ### end Alembic commands ###
