"""add waka_id to review

Revision ID: 9925713d972b
Revises: 9577a68c966d
Create Date: 2026-04-04 03:07:17.620805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9925713d972b'
down_revision: Union[str, Sequence[str], None] = '9577a68c966d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('waka_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'wakas', ['waka_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'waka_id')
    # ### end Alembic commands ###
