"""Make reviews target generic user

Revision ID: a03e3db62055
Revises: 885f1ca3d905
Create Date: 2026-04-02 04:52:22.082657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a03e3db62055'
down_revision: Union[str, Sequence[str], None] = '885f1ca3d905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('target_user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('reviews_runner_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['target_user_id'], ['id'])
    op.drop_column('reviews', 'runner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('runner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_runner_id_fkey'), 'reviews', 'runner_profiles', ['runner_id'], ['id'])
    op.drop_column('reviews', 'target_user_id')
    # ### end Alembic commands ###
