"""unify_user_runner

Revision ID: bad4ea85ac71
Revises: b42c925d2b7c
Create Date: 2026-04-02 22:46:40.338137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bad4ea85ac71'
down_revision: Union[str, Sequence[str], None] = 'b42c925d2b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns to users
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('stats_trips', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_users_is_online'), 'users', ['is_online'], unique=False)

    # 2. Data migration from runner_profiles to users
    op.execute("""
        UPDATE users 
        SET bio = rp.bio, 
            hourly_rate = rp.hourly_rate, 
            is_online = rp.is_online, 
            stats_trips = rp.stats_trips 
        FROM runner_profiles rp 
        WHERE users.id = rp.user_id
    """)

    # 3. Drop old table and indices
    op.drop_index(op.f('idx_runner_profiles_current_location'), table_name='runner_profiles', postgresql_using='gist')
    op.drop_index(op.f('ix_runner_profiles_is_deleted'), table_name='runner_profiles')
    op.drop_index(op.f('ix_runner_profiles_is_online'), table_name='runner_profiles')
    op.drop_table('runner_profiles')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_online'), table_name='users')
    op.drop_column('users', 'stats_trips')
    op.drop_column('users', 'is_online')
    op.drop_column('users', 'hourly_rate')
    op.drop_column('users', 'bio')
    op.create_table('runner_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True),
    sa.Column('stats_trips', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stats_rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('2.5'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('runner_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('runner_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('runner_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_runner_profiles_is_online'), 'runner_profiles', ['is_online'], unique=False)
    op.create_index(op.f('ix_runner_profiles_is_deleted'), 'runner_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_runner_profiles_current_location'), 'runner_profiles', ['current_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
