"""add_metadata_and_deleted_to_message

Revision ID: ecb14ff8c331
Revises: 1a050cce0bf1
Create Date: 2026-04-03 05:12:38.603105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb14ff8c331'
down_revision: Union[str, Sequence[str], None] = '1a050cce0bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachment_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.drop_column('messages', 'attachment_metadata')
    # ### end Alembic commands ###
