"""Add is_otp_verified

Revision ID: f3e1ada82d8d
Revises: 1da4a817b900
Create Date: 2026-04-02 04:35:42.881430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f3e1ada82d8d'
down_revision: Union[str, Sequence[str], None] = '1da4a817b900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_otp_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_otp_verified')
    # ### end Alembic commands ###
