"""add_last_location_to_user

Revision ID: f81878c9c706
Revises: 43fb967e5649
Create Date: 2026-04-02 21:26:24.384113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f81878c9c706'
down_revision: Union[str, Sequence[str], None] = '43fb967e5649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.execute("DROP INDEX IF EXISTS idx_users_last_location")
    op.create_index('idx_users_last_location', 'users', ['last_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_last_location', table_name='users', postgresql_using='gist')
    op.drop_column('users', 'last_location')
    # ### end Alembic commands ###
