"""add payment_method to waka

Revision ID: f933e2ddf2d6
Revises: fca2ad597e1f
Create Date: 2026-04-05 04:51:59.912540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f933e2ddf2d6'
down_revision: Union[str, Sequence[str], None] = 'fca2ad597e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wakas', sa.Column('payment_method', sa.String(length=20), server_default='wallet', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wakas', 'payment_method')
    # ### end Alembic commands ###
